### ISSUE TITLE
RustHoverActions doesn't work for async main functions and tests

### ISSUE THREAD

**Issue by poljar** [simrat39/rust-tools.nvim#247]
Tokio, and other async runtimes, tend to have nice macros to use async functions as a main function or as a test. Async functions annotated with `#[tokio::main]` and `#[tokio::test]` can be used normally as the main function and test functions respectively without any additional setup.

Those functions can be run and debugged with `vim.lsp.codelens.refresh()` and `vim.lsp.codelens.run()` lua method just fine:

![image](https://user-images.githubusercontent.com/552026/187697937-636cbdd4-d087-4c02-ae8d-822ee4f6fdc9.png)

However, `RustHoverActions` doesn't display anything sensible:

![image](https://user-images.githubusercontent.com/552026/187698182-66c6f1bf-f99e-4ec9-be94-e543b13c5ce2.png)

`RustHoverActions` works fine if we convert the method back to a non-async one and do the async plumbing `#[tokio::main]` does for us manually:

![image](https://user-images.githubusercontent.com/552026/187699141-80100aa2-e7a7-459d-9e73-ed96d49bd1ed.png)

The minimal reproducer is:

```rust
use std::time::Duration;

#[tokio::main]
async fn main() {
    println!("Sleeping, world!");
    tokio::time::sleep(Duration::from_secs(10)).await;
    println!("Hello, world!");
}
```

While the working non-async variant is:

```rust
use std::time::Duration;

fn main() -> anyhow::Result<()> {
    let runtime = tokio::runtime::Runtime::new()?;

    runtime.block_on(async {
        println!("Sleeping, world!");
        tokio::time::sleep(Duration::from_secs(10)).await;
        println!("Hello, world!");
    });

    Ok(())
}
```

Both work with the following `Cargo.toml` file:

```toml
[package]
name = "test-tokio-rust-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
tokio = { version = "1.20.1", features = ["rt-multi-thread", "macros", "time"] }
```
